name: Build Documentatiion

on:
  pull_request:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - run: zig build test --summary all
      - name: Build examples
        working-directory: examples
        run: zig build-lib -femit-docs src/webrtc.zig 